applicationApiVersion: v1beta1
applicationKind: Application

# Adapted from postgresql's schema.yaml
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  xtdb.serviceAccount:
    type: string
    title: XTDB Service Account
    description: "Service account with Storage Admin permissions for XTDB"
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: edit
  gcpProjectId:
    type: string
    title: GCP Project ID
    description: "GCP Project ID where your storage bucket is located"
  gcpBucket:
    type: string
    title: GCP Storage Bucket
    description: "GCP Storage Bucket for XTDB data (must be created beforehand)"
  kafkaBootstrapServers:
    type: string
    title: Kafka Bootstrap Servers
    description: "Kafka bootstrap servers (leave default if using included Kafka)"
    default: "kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
  kafkaLogTopic:
    type: string
    title: Kafka Log Topic
    description: "XTDB log topic on Kafka"
    default: "xtdb-log"
  kafka.enabled:
    type: boolean
    title: Deploy Kafka
    description: "Deploy Kafka as part of this installation"
    default: true
  xtdb.persistence.storageClass:
    type: string
    title: StorageClass
    description: StorageClass for XTDB persistent volumes
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
  xtdb.persistence.size:
    type: string
    title: Storage size for persistent volumes
    default: "50Gi"
    description: XTDB local disk cache size
    pattern: '^[1-9][0-9]*(\.[0-9]+)?[TGM]i?$'
  tls.keystorePassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  tls.enabled:
    type: boolean
    title: Enable TLS Security
    description: Enable TLS secure communication for XTDB
    default: true
required:
  - name
  - namespace
  - xtdb.serviceAccount
  - gcpProjectId
  - gcpBucket
  - tls.keystorePassword