apiVersion: v2
name: xtdb
description: XTDB for Google Cloud
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: kafka
  version: 31.3.1
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled