name: XTDB Edge

on:
  workflow_dispatch:

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  remove-untagged:
    runs-on: ubuntu-latest
    steps:
      - name: purge untagged packages
        uses: Chizkiyahu/delete-untagged-ghcr-action@v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner_type: org
          untagged_only: true
    permissions:
      packages: write
